after_success: 
- coveralls
install: 
- test -d pip.cache || git clone --depth 1 git://github.com/qdamian/dissect.pip.cache pip.cache
- pip install --no-index --find-links=pip.cache -r requirements.txt -r dev-requirements.txt --quiet
- pip install -r requirements.txt --use-mirrors --quiet
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: 
- pylint --errors-only --rcfile=.pylintrc dissect
- nosetests --config .noserc
- rm -rf build
- python setup.py sdist
- python setup.py install
- behave test/system/features
python: 
- 2.7
language: python
deploy: 
  password: 
    secure: pIvc0o8M0bg/CPCb3yXb6+rZWZPCcgq6X8AslKIHmx8rvaEIQZC/fhKxGIrROIFOHLSEWrPzeblJWweSwDVSwOtFj30uLpFLrC0V2kR4uoNoiOjXmAHweYD1j9gvQvB/xkDNFgHkpG5wX8jxwMiGb6dFn83AfXsBYY75bYklSW4=
  on: 
    tags: true
  server: https://testpypi.python.org/pypi
  provider: pypi
  user: qdamian
