language: python
python:
  - 2.7
install:
  # Dependencies
    - pip install -r requirements.txt --use-mirrors --quiet
    # Workaround https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  # Lint
    - pylint --rcfile=.pylintrc dissect
  # Unit test
    - nosetests --config .noserc
  # Build
    - rm -rf build
    - python setup.py sdist
  # Install
    - python setup.py install
  # Integration test
    - behave test/system/features
after_success:
  # Report
    - coveralls
