python: 
- 2.7
script: 
- pylint --errors-only --rcfile=.pylintrc dissect
- nosetests --config .noserc
- rm -rf build
- python setup.py sdist
- python setup.py install
- behave test/system/features
language: python
install: 
- test -d pip.cache || git clone --depth 1 git://github.com/qdamian/dissect.pip.cache pip.cache
- pip install --no-index --find-links=pip.cache -r requirements.txt -r dev-requirements.txt --quiet
- pip install -r requirements.txt --use-mirrors --quiet
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
after_success: 
- coveralls
deploy: 
  on: 
    tags: true
  password: 
    secure: QdyfuOlKoznaZaqQMThGDKB4sOv9xAGiO47Jqrq0fEQBplRVsJzG/IgdMP8I1C42v6ayGnptdGanrstVuUNlpl7FZLjLXPf8ZtKxGAllajHSZs46lqslik4njC5kA0OjE+GMjeTaFZXY1/O0FtDEI2WIeVbW5ORyVF//QXA0IJw=
  server: https://testpypi.python.org/pypi
  user: qdamian
  provider: pypi
