deploy: 
  password: 
    secure: Tvba7OA7pgsnf0PYggfwy/A1wq4QUr3B48nhKvKA9CisSoLrnxoWKQoKIUptwNiLRmKjRzBXlwYw6UC27Mxj8srFfu46WuSLPt9doP3K75NLCIQdnmtWp3s4XQnCM7IjBIB4jqicQzg4EQqQyaNVusc40ro6NoQ2swRV/apmnIE=
  server: https://testpypi.python.org/pypi
  on: 
    tags: true
  user: qdamian
  provider: pypi
python: 
- 2.7
script: 
- pylint --errors-only --rcfile=.pylintrc dissect
- nosetests --config .noserc
- rm -rf build
- python setup.py sdist
- python setup.py install
- behave test/system/features
install: 
- test -d pip.cache || git clone --depth 1 git://github.com/qdamian/dissect.pip.cache pip.cache
- pip install --no-index --find-links=pip.cache -r requirements.txt -r dev-requirements.txt --quiet
- pip install -r requirements.txt --use-mirrors --quiet
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
language: python
after_success: 
- coveralls
